CREATE DATABASE SUPERMERCADO;
CREATE TABLE PRODUTO (
	CODIGO_PRO INT AUTO_INCREMENT PRIMARY KEY,
	NOME_PRO VARCHAR (60) NOT NULL,
	VALOR_PRO FLOAT NOT NULL
);

CREATE TABLE FORNECEDOR (
	CNPJ CHAR (17) PRIMARY KEY, -- "99.999.999.9999-9"
	NOME_FOR VARCHAR (60) NOT NULL,
	TELEFONE_FOR VARCHAR (12) NOT NULL, -- 00 0000-0000
	ENDERECO_FOR VARCHAR (160) NOT NULL,
	EMAIL_FOR VARCHAR (60) NOT NULL
);

CREATE TABLE VENDA (
	CODIGO_VENDA INT PRIMARY KEY AUTO_INCREMENT,
	DATAVENDA DATE NOT NULL,
	HORA_VENDA TIME NOT NULL,
	TOTAL_VENDA FLOAT NOT NULL
);

CREATE TABLE PESSOA(
	NOME_PESSOA VARCHAR (60) NOT NULL,
	CPF_PESSOA CHAR (14) NOT NULL, -- 000.000.000-00
	SEXO_PESSOA CHAR (1) NOT NULL,
	ENDERECO_PESSOA VARCHAR (80) NOT NULL,
	TELEFONE_PESSOA (12)
);

CREATE TABLE FUNCIONARIO (
CODIGO_FUN INT AUTO_INCREMENT
);

CREATE TABLE CLIENTE (
CODIGO_CLI INT AUTO_INCREMENT
);

CREATE TABLE ITEMVENDA (
QUANTIDADE INT NOT NULL,
PRECO FLOAT NOT NULL,
--VENDAS  VENDA
--PRODUTO PRODUTO
);